In [1]:
import pandas as pd
from pandas import DataFrame, Series

In [106]:
info = [0, 8, 0, 0, 0, 0, 2, 0, 0, 
        0, 0, 0, 0, 8, 4, 0, 9, 0, 
        0, 0, 6, 3, 2, 0, 0, 1, 0, 
        0, 9, 7, 0, 0, 0, 0, 8, 0, 
        8, 0, 0, 9, 0, 3, 0, 0, 2, 
        0, 1, 0, 0, 0, 0, 9, 5, 0, 
        0, 7, 0, 0, 4, 5, 8, 0, 0, 
        0, 3, 0, 7, 1, 0, 0, 0, 0, 
        0, 0, 8, 0, 0, 0, 0, 4, 0]

In [107]:
import numpy as np

def calc_possible(puzzle, ele):
    data = puzzle.iloc[ele, :]
    working = puzzle[(puzzle['r'] == data['r']) & (puzzle['c'] == data['c'])]['current']
    if int(working) != 0:
        return [int(working)]
    else:
        invalid = pd.concat([puzzle[puzzle['r'] == data['r']].loc[:, 'current'], 
                             puzzle[puzzle['c'] == data['c']].loc[:, 'current'], 
                             puzzle[puzzle['p'] == data['p']].loc[:, 'current']
                             ])
        return np.array([i for i in range(1, 10) if i not in invalid.unique()])
    
    

In [108]:
from itertools import chain
from itertools import repeat

values = [i for i in range(1, 10)]
r = list(chain.from_iterable(repeat(i, 9) for i in range(0, 9)))
c = [i for i in range(0, 9)]*9
puzzle = DataFrame(data={'r': list(chain.from_iterable(repeat(i, 9) for i in range(0, 9))), 
                         'c':[i for i in range(0, 9)]*9, 
                         'p': [i//3*3 + j//3 for i, j in zip(r, c)], 
                         'current': info
                         })


puzzle['possible'] = [calc_possible(puzzle, i) for i in range(puzzle.shape[0])]
puzzle['current'] = 0

In [103]:
mapping = np.arange(81).reshape(9, 9)
# mapping[81//9, 81%9]
mapping[70//9-70//9%3:70//9, 70%9 - 70%3:70%9 - 70%3 +3]

array([[60, 61, 62]])

In [110]:
mapping

array([[7., 8., 4., 1., 9., 6., 2., 3., 5.],
       [3., 2., 1., 5., 8., 4., 6., 9., 7.],
       [9., 5., 6., 3., 2., 7., 4., 1., 8.],
       [2., 9., 7., 4., 5., 1., 3., 8., 6.],
       [8., 4., 5., 9., 6., 3., 1., 7., 2.],
       [6., 1., 3., 8., 7., 2., 9., 5., 4.],
       [1., 7., 9., 6., 4., 5., 8., 2., 3.],
       [4., 3., 2., 7., 1., 8., 5., 6., 9.],
       [5., 6., 8., 2., 3., 9., 7., 4., 1.]])

In [109]:
i = 0
mapping = np.zeros((9, 9))
while i != 81:
    # previous mistake, backing up
    if mapping[i//9, i % 9] == np.max(puzzle.iat[i, 4]):
        mapping[i//9, i % 9] = 0
        i -= 1
        continue
    
    # empty spot
    elif mapping[i//9, i%9] == 0:
        mapping[i//9, i%9] = puzzle.iat[i, 4][0]
        
    # assign next possible value
    else:
        next_value = np.argwhere(puzzle.iat[i, 4] == mapping[i//9, i%9])
        mapping[i//9, i%9] = puzzle.iat[i, 4][next_value+1]
           
    if mapping[i//9, i%9] in mapping[i//9, 0:i%9] or \
            mapping[i//9, i%9] in mapping[0:i//9, i%9] or \
            mapping[i//9, i%9] in mapping[i//9-i//9%3:i//9, i%9 - i%3:i%9 - i%3 +3]:
        continue
    else:
        # print('moving on')
        i += 1
print(puzzle)

    r  c  p  current            possible
0   0  0  0        0  [1, 3, 4, 5, 7, 9]
1   0  1  0        0                 [8]
2   0  2  0        0     [1, 3, 4, 5, 9]
3   0  3  1        0           [1, 5, 6]
4   0  4  1        0        [5, 6, 7, 9]
5   0  5  1        0        [1, 6, 7, 9]
6   0  6  2        0                 [2]
7   0  7  2        0           [3, 6, 7]
8   0  8  2        0     [3, 4, 5, 6, 7]
9   1  0  0        0     [1, 2, 3, 5, 7]
10  1  1  0        0              [2, 5]
11  1  2  0        0        [1, 2, 3, 5]
12  1  3  1        0           [1, 5, 6]
13  1  4  1        0                 [8]
14  1  5  1        0                 [4]
15  1  6  2        0        [3, 5, 6, 7]
16  1  7  2        0                 [9]
17  1  8  2        0        [3, 5, 6, 7]
18  2  0  0        0        [4, 5, 7, 9]
19  2  1  0        0              [4, 5]
20  2  2  0        0                 [6]
21  2  3  1        0                 [3]
22  2  4  1        0                 [2]
23  2  5  1     

In [241]:

# 3 in puzzle.iloc[0, :]['possible']
# np.any(puzzle[(puzzle['r'] == puzzle.iloc[0, :]['r']) & (puzzle['current'] != 0)].loc[:, 'current'].duplicated())
puzzle.head()
# puzzle.iat[0, 3] = 6
# print(puzzle.iat[0, 3])
np.argwhere(puzzle.iloc[i, :]['possible'] == puzzle.iat[i, 3])

array([[1]], dtype=int64)

In [279]:
 puzzle

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>r</th>
      <th>c</th>
      <th>p</th>
      <th>current</th>
      <th>possible</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>[1, 3, 4, 5, 7, 9]</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>8</td>
      <td>[8]</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>2</td>
      <td>0</td>
      <td>4</td>
      <td>[1, 3, 4, 5, 9]</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>3</td>
      <td>1</td>
      <td>5</td>
      <td>[1, 5, 6]</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>4</td>
      <td>1</td>
      <td>9</td>
      <td>[5, 6, 7, 9]</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0</td>
      <td>5</td>
      <td>1</td>
      <td>7</td>
      <td>[1, 6, 7, 9]</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0</td>
      <td>6</td>
      <td>2</td>
      <td>2</td>
      <td>[2]</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0</td>
      <td>7</td>
      <td>2</td>
      <td>6</td>
      <td>[3, 6, 7]</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0</td>
      <td>8</td>
      <td>2</td>
      <td>3</td>
      <td>[3, 4, 5, 6, 7]</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>[1, 2, 3, 5, 7]</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1</td>
      <td>1</td>
      <td>0</td>
      <td>5</td>
      <td>[2, 5]</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1</td>
      <td>2</td>
      <td>0</td>
      <td>2</td>
      <td>[1, 2, 3, 5]</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1</td>
      <td>3</td>
      <td>1</td>
      <td>1</td>
      <td>[1, 5, 6]</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1</td>
      <td>4</td>
      <td>1</td>
      <td>8</td>
      <td>[8]</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1</td>
      <td>5</td>
      <td>1</td>
      <td>4</td>
      <td>[4]</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1</td>
      <td>6</td>
      <td>2</td>
      <td>5</td>
      <td>[3, 5, 6, 7]</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1</td>
      <td>7</td>
      <td>2</td>
      <td>0</td>
      <td>[9]</td>
    </tr>
    <tr>
      <th>17</th>
      <td>1</td>
      <td>8</td>
      <td>2</td>
      <td>0</td>
      <td>[3, 5, 6, 7]</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>[4, 5, 7, 9]</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>[4, 5]</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2</td>
      <td>2</td>
      <td>0</td>
      <td>0</td>
      <td>[6]</td>
    </tr>
    <tr>
      <th>21</th>
      <td>2</td>
      <td>3</td>
      <td>1</td>
      <td>0</td>
      <td>[3]</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2</td>
      <td>4</td>
      <td>1</td>
      <td>0</td>
      <td>[2]</td>
    </tr>
    <tr>
      <th>23</th>
      <td>2</td>
      <td>5</td>
      <td>1</td>
      <td>0</td>
      <td>[7, 9]</td>
    </tr>
    <tr>
      <th>24</th>
      <td>2</td>
      <td>6</td>
      <td>2</td>
      <td>0</td>
      <td>[4, 5, 7]</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2</td>
      <td>7</td>
      <td>2</td>
      <td>0</td>
      <td>[1]</td>
    </tr>
    <tr>
      <th>26</th>
      <td>2</td>
      <td>8</td>
      <td>2</td>
      <td>0</td>
      <td>[4, 5, 7, 8]</td>
    </tr>
    <tr>
      <th>27</th>
      <td>3</td>
      <t