In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [2]:
info = np.array([[0, 8, 0, 0, 0, 0, 2, 0, 0], 
                 [0, 0, 0, 0, 8, 4, 0, 9, 0], 
                 [0, 0, 6, 3, 2, 0, 0, 1, 0], 
                 [0, 9, 7, 0, 0, 0, 0, 8, 0], 
                 [8, 0, 0, 9, 0, 3, 0, 0, 2], 
                 [0, 1, 0, 0, 0, 0, 9, 5, 0], 
                 [0, 7, 0, 0, 4, 5, 8, 0, 0], 
                 [0, 3, 0, 7, 1, 0, 0, 0, 0], 
                 [0, 0, 8, 0, 0, 0, 0, 4, 0]])

In [3]:
def possible(info):
    for ele in range(81):
        if info[ele//9, ele%9] != 0:
            yield np.array([info[ele//9, ele%9]])
        else:
            invalid = np.unique(np.concatenate([info[ele//9, :], 
                                                info[:, ele%9], 
                                                info[ele//9-ele//9 % 3: ele//9-ele//9 % 3+3, 
                                                     ele % 9-ele % 3: ele % 9-ele % 3+3
                                                    ].flatten()
                                                ]))
            yield np.array([i for i in range(1, 10) if i not in invalid])
            
            
puzzle = DataFrame(data={'possible': [x for x in possible(info)]})

In [34]:
mapping

array([[7., 8., 4., 1., 9., 6., 2., 3., 5.],
       [3., 2., 1., 5., 8., 4., 6., 9., 7.],
       [9., 5., 6., 3., 2., 7., 4., 1., 8.],
       [2., 9., 7., 4., 5., 1., 3., 8., 6.],
       [8., 4., 5., 9., 6., 3., 1., 7., 2.],
       [6., 1., 3., 8., 7., 2., 9., 5., 4.],
       [1., 7., 9., 6., 4., 5., 8., 2., 3.],
       [4., 3., 2., 7., 1., 8., 5., 6., 9.],
       [5., 6., 8., 2., 3., 9., 7., 4., 1.]])

In [38]:
# %%timeit 
i = 0
mapping = np.zeros((9, 9))
while i != 81:
    # previous mistake, backing up
    possibles = puzzle.iat[i, 0]
    
    if mapping[i//9, i % 9] == np.max(possibles):
        mapping[i//9, i % 9] = 0
        i -= 1
        continue
    else:
        set_possibles = set(possibles[np.where(possibles > mapping[i//9, i%9])])        
        invalid = set(np.concatenate([mapping[i//9, 0:i%9],
                                      mapping[0:i//9, i%9],
                                      mapping[i//9-i//9%3:i//9, i%9 - i%3:i%9 - i%3 + 3].flatten()
                                     ]))

        results = set_possibles - invalid
        if len(results) == 0:
            mapping[i//9, i%9] = 0
            i -= 1
        else:
            mapping[i//9, i%9] = min(results)
            i += 1

print(mapping)

[[7. 8. 4. 1. 9. 6. 2. 3. 5.]
 [3. 2. 1. 5. 8. 4. 6. 9. 7.]
 [9. 5. 6. 3. 2. 7. 4. 1. 8.]
 [2. 9. 7. 4. 5. 1. 3. 8. 6.]
 [8. 4. 5. 9. 6. 3. 1. 7. 2.]
 [6. 1. 3. 8. 7. 2. 9. 5. 4.]
 [1. 7. 9. 6. 4. 5. 8. 2. 3.]
 [4. 3. 2. 7. 1. 8. 5. 6. 9.]
 [5. 6. 8. 2. 3. 9. 7. 4. 1.]]
